#!/bin/bash
set -e

configure_nodenv() {
  echo "--> Installing latest version of nodejs:"

  NODE_LATEST_VERSION=$(nodenv install -l | grep -v - | grep "^[0-9]" | tail -1)

  nodenv install "$NODE_LATEST_VERSION"
  nodenv global "$NODE_LATEST_VERSION"
  nodenv rehash
}

configure_rbenv() {
  echo "--> Installing latest version of ruby:"

  RUBY_LATEST_VERSION=$(rbenv install -l | grep -v - | grep "^[0-9]" | tail -1)

  rbenv install "$RUBY_LATEST_VERSION"
  rbenv global "$RUBY_LATEST_VERSION"
  rbenv rehash

  gem install bundler cocoapods
}

main () {
  configure_rbenv
  configure_nodenv
}

main $@