#!/bin/bash

SSH_CONFIG_FILE="$HOME/.ssh/config"

SCRIPTS_DIR=$(dirname $0)
cd $SCRIPTS_DIR/..
DOTFILES_DIR=$(pwd -P)

configure_ssh () {
  echo "--> Preparing SSH configuration."
  # Setup SSH & Git
  if [ ! -f "$HOME/.ssh/id_ed25519" ]; then
      ssh-keygen -t ed25519 -C "${SSH_KEY_EMAIL-fred@ephread.com}"

      if [ ! -f "$SSH_CONFIG_FILE" ]; then
          touch "$SSH_CONFIG_FILE"
          cat >> "$SSH_CONFIG_FILE" <<- EOM
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOM
      fi
  fi
}

main () {
  "$SCRIPTS_DIR/configure-xcode"
  "$SCRIPTS_DIR/configure-vscode"
  "$SCRIPTS_DIR/configure-rbenv-nodenv"

  configure_ssh

  sudo chsh -s /bin/zsh fred
}

main $@